### ISSUE TITLE
key-value pair subcommands

### ISSUE THREAD

**Issue by ghost** [krismuniz/slash-command#1]
Cool module you got there, I'd like to request a feature. Subcommands as key-value pair.

Ex. `/sendMail/to=john.doe@domain.com/title=meeting meet me at the park @ 8pm` would return:

``` js
{
  slashcommand: '/sendMail',
  command: 'sendMail',
  subcommands: [
    { to: 'john.doe@domain.com' },
    { title: 'meeting' }
  ],
  body: 'meet me at the park @ 8pm',
  original: '/sendMail/to=john.doe@domain.com/title=meeting meet me at the park @ 8pm'
}
```

**Comment by krismuniz** [comment]
Hello @vkeusebio! As much as I would like to add that feature, I am afraid that would be out of this module's scope; I don't want to add too much complexity to it. Also, it would differ a lot from its initial intended specifications and would break any project that depends on it (e.g. a couple of my projects expect `subcommands` to be an array of strings).

_However_, I did find that it did not match some symbols that might become handy (`.`, `@`, `:`, and `=`), so I updated the module to match these as valid command/subcommand characters. So, thank you for that!

**If you really need those key-value pairs, you can do something like this:**

``` js
const slashCommand = require('slash-command')

slashCommand('/sendMail/to=john.doe@domain.com/title=meeting meet me at the park @ 8pm')
  .subcommands
  .map((value) => {
    let obj = {}
    obj[value.split('=')[0]] = value.split('=')[1]
    return obj
  })
```

This will return an array containing the key-value pairs extracted from the `subcommands` property of the object returned by `slashCommand()`:

``` js
[ { to: 'john.doe@domain.com' }, { title: 'meeting' } ]
```

I hope this helps :smiley:

**Comment by ghost** [comment]
Oh, I understand, thank you for the trick :+1:

**Comment by krismuniz** [comment]
No problem :D
